name: Integration
"on":
  push:
    branches:
      - master
  pull_request: {}
permissions:
  contents: read
concurrency:
  group: "integration-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  e2e:
    name: "E2E (${{ matrix.os }})"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: "false"
      - name: Set up Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed
        with:
          deno-version: v2.x
      - name: Run the subprocess e2e suite
        run: deno run -A zuke.ts integration
