name: Scorecard supply-chain
"on":
  push:
    branches:
      - master
  branch_protection_rule: {}
  schedule:
    - cron: "18 3 * * 2"
permissions:
  contents: read
jobs:
  scorecardSarif:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: Harden and check out with Zuke
        uses: zuke-build/zuke@7a62523bb4569e4d90e972dee74bf9cf09cd436f # v1.0.1
        with:
          egress-policy: audit
          persist-credentials: "false"
      - name: Run Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: "true"
      - name: Run scorecardSarif with Zuke
        run: ./zuke scorecardSarif
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
