trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main
jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: ./zuke
        displayName: Build
